config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/TREX-CoE/qmckl:
      branch: master
      repo: https://github.com/TREX-CoE/qmckl
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/TREX-CoE/qmckl git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-myrtle-squirrel.sh
        container: qc.acc_sickly-aqua-fish
  QC.Doc:
    repos:
      github.com/TREX-CoE/qmckl find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-grey-lobster.sh
        container: qc.doc_stuffy-viridian-zebu
      github.com/TREX-CoE/qmckl git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-pumpkin-labradoodle.sh
        container: qc.doc_wiggy-auburn-squirt
      github.com/TREX-CoE/qmckl markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-silver-donkey.sh
        container: qc.doc_squeaky-olive-hippopotamus
  QC.Lic:
    repos:
      github.com/TREX-CoE/qmckl licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-ecru-bird.sh
        container: qc.lic_tacky-orange-husky
  QC.Sec:
    repos:
      github.com/TREX-CoE/qmckl bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-olivine-seahorse.sh
        container: qc.sec_pasty-heliotrope-pig
  QC.Sty:
    repos:
      github.com/TREX-CoE/qmckl flake8:
        commands:
        - /usr/bin/env sh .sqa/script.randy-carmine-hedgehog.sh
        container: qc.sty_shaggy-amethyst-moorhen
      github.com/TREX-CoE/qmckl jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-grey-sloth.sh
        container: qc.sty_chummy-corn-gerbil
  QC.Uni:
    repos:
      github.com/TREX-CoE/qmckl pytest:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-cardinal-monster.sh
        container: qc.uni_sloppy-thistle-fousek
  QC.Ver:
    repos:
      github.com/TREX-CoE/qmckl get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-goldenrod-harrier.sh
        container: qc.ver_snappy-buff-fossa
timeout: 5400
